create table if not exists public.diagnostics (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  visitor_id text not null,
  background text not null,
  experience text not null,
  input text not null,
  output jsonb not null,
  input_tokens integer,
  output_tokens integer,
  top_skills jsonb not null default '[]'::jsonb,
  refused boolean not null default false
);

create index if not exists diagnostics_visitor_created_idx
  on public.diagnostics (visitor_id, created_at desc);

alter table public.diagnostics enable row level security;

-- The website never receives a Supabase key. Only the Vercel serverless functions
-- use the service-role key, so no public table policy is required.
